MPESA_CONSUMER_KEY: "cCdoyvJ5us7qeFk9vnjmqKJ7GyDwvaeH"
MPESA_CONSUMER_SECRET: "sQUpA9YGDOPTKYLL"
MPESA_PASSKEY: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
MPESA_SHORTCODE: "174379"
MPESA_INITIATOR_NAME: "testapi"
MPESA_INITIATOR_PASSWORD: "Safaricom999!*!"
CALLBACK_URL: "https://285c-102-215-76-91.in.ngrok.io"
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"
