name: "GrubHub CI"
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: grubhub
    steps:
    - name: Set up Ruby
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
#         bundler-cache: true 
    - name: Install dependencies
    - run: bundle install
    - name: Set up database
    - run: bundle exec rails db:setup
